---
title: "RTP"
format: html
editor: visual
---

## libraries

```{r}
library(readr)
library(readxl)
library(dplyr)
library(rmarkdown)
library(tidyverse)
library(sf)
library(stringr)
library(mapview)
library(lubridate)
library(scales)
library(rfishbase)
library(leaflet)
```


# importation des données RTP
```{r}

pro_data <- read_csv("data/pro/pro_data.csv")


#données SIH 
RTP_SIH <- read_delim(file="data/raw/ISIH-501892-taille_poids-20220131174507/ISIH-501892-taille_poids-20220131174507.txt", delim=";")

#données fishbase 
RTP_fishbase<- length_weight(
  species_list =espece_peche$NomScientifique
)

# données ObsBio
obsBio <- read_delim("data/raw/obsBio.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

```
# Taille min de capture
```{r}
taille_banyuls <- read_delim("data/raw/taille_banyuls.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE,  locale = locale(encoding = "latin1"))
taille_calanque <- read_excel("data/raw/taille_calanque.xlsx")
taille_cap_corse <- read_excel("data/raw/taille_cap_corse.xlsx")
taille_pmngl <- read_delim("data/raw/taille_pmngl.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE, locale = locale(encoding = "latin1"))
#taille_bonifacio a faire 



tailles_capture <- bind_rows(
  taille_banyuls  %>% select(NomScientifique, taille_min_MM) %>% mutate(ID_ZoneDePeche = "Banyuls"),
  taille_calanque %>% select(NomScientifique, taille_min_MM) %>% mutate(ID_ZoneDePeche = "Calanque"),
  taille_cap_corse %>% select(NomScientifique, taille_min_MM) %>% mutate(ID_ZoneDePeche = "CapCorse"),
  taille_pmngl %>% select(NomScientifique, taille_min_MM)   %>% mutate(ID_ZoneDePeche = "PNMGL")
)

tailles_capture <- tailles_capture %>%
  select(NomScientifique, ID_ZoneDePeche, taille_min_MM) %>%
  distinct(NomScientifique, ID_ZoneDePeche, .keep_all = TRUE) %>%  # 1 valeur par espèce × zone
  pivot_wider(
    id_cols    = NomScientifique,
    names_from = ID_ZoneDePeche,
    values_from = taille_min_MM
  )
```

#données SIH

```{r}
# dans les données on ne garde en premier que les RTP de mediterranée : code 37 et 3712
RTP_Med <- RTP_SIH %>% 
	filter(NOM_VALIDE %in% pro_data$NomScientifique) %>%
	filter(SECT_COD %in% c("37", "3712")) %>%
	filter(TMESURE_COD=="LENGTH_TOTAL") %>%
  mutate(origine ="med")

# ensuite on va dans le reste des données pour aller chercher les données des espèces qui n'étaient pas dans MED
RTP_autres <- RTP_SIH %>% 
	filter(NOM_VALIDE %in% pro_data$NomScientifique) %>%
	filter(! NOM_VALIDE %in% RTP_Med$NOM_VALIDE) %>%
	filter(TMESURE_COD=="LENGTH_TOTAL")%>%
  mutate(origine ="hors med")


RTP_SIH <- bind_rows(RTP_Med, RTP_autres)


# il y a plusieurs ratio par espèces : tri pour garder les ratios les plus adaptés 

# 1er tri : quand plusieurs lignes =, n'en garder qu'une : 
RTP_SIH <- RTP_SIH %>% 
  distinct(NOM_VALIDE, RTP_COEF_A_CM, RTP_COEF_B, .keep_all = T)

# 2eme tri : quand lignes différentes, gqrder le ratio le plus récent : 
RTP_SIH <- RTP_SIH %>%
  group_by(NOM_VALIDE) %>%
  slice_max( ANNEE, n=1) %>%
  ungroup()

# 3ème tri : moyenne des ratio restants

RTP_SIH<- RTP_SIH %>%
  group_by(NOM_VALIDE) %>%
  mutate(RTP_COEF_A_CM = mean(RTP_COEF_A_CM, na.rm= TRUE), RTP_COEF_B= mean(RTP_COEF_B, na.rm= TRUE) )%>%
  slice(1)%>%
  ungroup()



# Regarder quelles espèces de notre jeu de données n'est pas dans les RTP_SIH : 

absente_RTP_SIH <- pro_data %>%
  filter(!NomScientifique %in% RTP_SIH$NOM_VALIDE)%>%
  distinct(NomScientifique) %>%
  pull(NomScientifique)
  

```

#données fishbase 

```{r}
# dans la base de donnée, on ne garde que les données de mediterranée : donc tri par les pays cotiers et le nom des mers. 

RTP_fb_med <- RTP_fishbase %>%
  filter(Type == "TL") %>%
  filter(str_detect(Locality, regex("mediterranean|spain|italy|greece|france|adriatic", ignore_case = TRUE))) %>%
  mutate(origine = "med")

# espèces que je n'ai pas pour la med mais que j'ai dans mes données 

RTP_fb_autres <- RTP_fishbase %>% 
  filter(Type == "TL") %>%
  filter(!Species %in% RTP_fb_med$Species)%>%
  mutate(origine = "hors med")

RTP_fishbase <- bind_rows(RTP_fb_autres, RTP_fb_med)

# il y a plusieurs ratio par espèces : tri pour garder les ratios les plus adaptés 

# 1er tri : quand plusieurs lignes =, n'en garder qu'une : 

RTP_fishbase <- RTP_fishbase %>% 
  distinct(Species, a, b, CoeffDetermination, .keep_all = T)

#2ème tri : garder le r2 le plus fort 
RTP_fishbase <- RTP_fishbase %>%
  group_by(Species) %>%
  slice_max(CoeffDetermination, n=1) %>%
  ungroup()
  
# 3ème tri : moyenne des ratio 
RTP_fishbase<- RTP_fishbase %>%
  group_by(Species) %>%
  mutate(a = mean(a, na.rm= TRUE), b= mean(b, na.rm= TRUE) )%>%
  slice(1)%>%
  ungroup()

# on regarde les espèces qui ne sont pas dans la base de données fishbase : 
absente_RTP_fishbase<- pro_data %>%
  filter(!NomScientifique %in% RTP_fishbase$Species) %>%
  distinct(NomScientifique) %>%
  pull(NomScientifique)


```


#données Obsbio
```{r}


ratio<- obsBio %>%
  mutate(WEIGHT_VALUE_G = WEIGHT_VALUE *1000 )%>% # on met en g les poids 
  mutate(NomScientifique=SCIENTIFIC_NAME)%>% 
  filter(WEIGHT_METHOD_NAME == "Mesure par un observateur") %>%
  filter(LENGTH_TOTAL_METHOD_NAME == "Mesure au 1/2 cm par un observateur") %>%
  mutate(LogL = log10(LENGTH_TOTAL_VALUE)) %>%
  mutate(LogW = log10(WEIGHT_VALUE_G))%>%
  mutate(origine = "med")


RTP_obsbio <- ratio %>%
  group_by(NomScientifique) %>%
  group_modify(~ {
    mod <- lm(LogW ~ LogL, data = .x)
    data.frame(
      a = 10^coef(mod)[1],
      b = coef(mod)[2]
    )
  }) 

RTP_obsbio <- RTP_obsbio%>%
  inner_join(ratio, by="NomScientifique" )


absente_RTP_obsbio <- pro_data%>%
  filter(!NomScientifique %in% obsBio$SCIENTIFIC_NAME) %>%
  distinct(NomScientifique)%>%
  pull(NomScientifique)


```


# espèces sans RTP du tout 


```{r}

espece_manquante <- pro_data%>%
  select(NomVernaculaire, NomScientifique)%>%
  filter(NomScientifique %in% absente_RTP_fishbase & NomScientifique %in% absente_RTP_SIH & NomScientifique %in% absente_RTP_obsbio) %>%
  distinct(NomVernaculaire, NomScientifique)

espece_manquante<-espece_manquante%>%
  select(NomVernaculaire, NomScientifique)%>%
  left_join(espece_peche %>% select(NomVernaculaire, total))


write.csv(espece_manquante, "data/pro/espece_manquante.csv")


# les 10 espèces les plus pêchées sont-elles dans les données ? 

espece_top10_RTP <- espece_top10 %>%
  filter(!NomScientifique %in% RTP_fishbase$Species | !NomScientifique %in% RTP_Med$NOM_VALIDE)%>%
  distinct(NomScientifique)%>%
  pull(NomScientifique)


```





# tri tailles aberrantes

```{r}
# importation de l'excel avec les tailles max des espèces : fait à la main, donc à remettre à jour si de nouvelles espèces sont pêchées. si les noms scientifiques sont genre spp, la taille max de la plus grande sp du même genre du tableau est donnée

sp_taille_poids <- read_excel("data/raw/sp_taille_poids.xlsx")


#ajouter les tailles et poids max à pro_data 
pro_data <- pro_data %>%
  left_join(sp_taille_poids %>%
              select(NomScientifique, Taille_max_mm, Poids_max_g) %>%
              distinct(),
            by="NomScientifique")

# mettre en numeric les valeurs 
pro_data <- pro_data %>%
  mutate(Taille_max_mm= as.numeric(Taille_max_mm), 
         Poids_max_g= as.numeric(Poids_max_g))
  
  
#il faut d'abord enlever les lignes ou les prises sont multiples: on ne sait pas si la taille est moyenne ou max ou min, pareil pour le poids


data_prise_unique <- pro_data %>%
  filter(Nb_de_prises == 1)


#on enlève les tailles et les poids abérrants : donc ceux qui sont 10% au dessus de la taille et du poids max reportés : on les met dans un autre tableau pour les traiter plus tard. 


erreur_supp <- data_prise_unique %>%
  filter(
  (Taille_MM > Taille_max_mm * 1.1 & !is.na(Taille_max_mm)) |
  (Poids_g > Poids_max_g * 1.1 & !is.na(Poids_max_g) ) 
  )


erreur_inf <- data_prise_unique %>%
  left_join(tailles_capture %>% select( NomScientifique, Banyuls, PNMGL, CapCorse, Calanque),
            by = "NomScientifique") %>%
  mutate(taille_min_zone = case_when(
    ID_ZoneDePeche==1 ~ PNMGL, 
    ID_ZoneDePeche==4 ~ Calanque, 
    ID_ZoneDePeche==6 ~ CapCorse, 
    ID_ZoneDePeche==7 ~ Banyuls
  )) %>%
  filter(
  !is.na(taille_min_zone),
  Taille_MM < taille_min_zone * 0.9,
  Taille_MM > 0)
  


data_coherente <- data_prise_unique %>%
  
  left_join(tailles_capture %>% select(NomScientifique, Banyuls, PNMGL, CapCorse, Calanque),
            by = "NomScientifique") %>%
 
  mutate(taille_min_zone = case_when(
    ID_ZoneDePeche == 1 ~ PNMGL, 
    ID_ZoneDePeche == 4 ~ Calanque, 
    ID_ZoneDePeche == 6 ~ CapCorse, 
    ID_ZoneDePeche == 7 ~ Banyuls
  )) %>%
 
  filter(
    #  MAX : TAILLE et POIDS <= 110% des max (ou NA)
    (Taille_MM <= Taille_max_mm * 1.1 | is.na(Taille_max_mm)) &
    (Poids_g <= Poids_max_g * 1.1 | is.na(Poids_max_g)) &
    # MIN : Taille >= 90% de la taille min (ou pas de règle)
    (Taille_MM >= taille_min_zone * 0.9 | is.na(taille_min_zone) | Taille_MM ==0)
  )

# verification pour être sur que toutes les données sont quelque part dans un tableau et pas de doublons 
nrow(data_prise_unique) == nrow(erreur_supp) + nrow(erreur_inf) + nrow(data_coherente)

```





# analyses taille-poids


### RTP SIH 
```{r}
# avec les données SIH : 


data_coherente_SIH <- data_coherente %>%
  mutate(outlier_valeur= Taille_MM==0 | Poids_g==0) %>%
  
  left_join(RTP_SIH %>% select(NomScientifique=NOM_VALIDE, RTP_COEF_A_CM, RTP_COEF_B, origine)) %>% # ajouter les coeff  dans le tableau 
  
  mutate(Poids_RTP=RTP_COEF_A_CM*Taille_MM^RTP_COEF_B) %>% # calculer le poids théorique grâce aux données de taille et aux coeff 
  
  mutate(Poids_diff = abs(Poids_g- Poids_RTP)) %>% # diff entre poids reel et poids théo
  
  mutate(outlier_RTP=Poids_diff/Poids_RTP > 1) %>% # met dans outlier_rtp les lignes ou poids obs vs poids théo >100%
  
	mutate(outlier=outlier_valeur | outlier_RTP) %>% # rassemble les outlier de zéro et les outlier de poids 

  mutate(diag=ifelse(outlier_valeur, "Val. manquante", "val. ok")) %>%
	mutate(diag=ifelse(! outlier_valeur, paste0(diag, " / ", 
																							ifelse(is.na(outlier_RTP), "RTP inconnue", 
																										 ifelse(outlier_RTP, "RTP aberrante", 'RTP ok'))), diag))  
  
data_coherente_SIH_clean <- data_coherente_SIH %>%
  filter(!outlier_valeur) %>% # on enlève les outlier = true  : donc on enlève les lignes avec poids ou taille manquante
  group_by(NomVernaculaire, NomScientifique, CodeFAO) %>%
  summarise(
    Taille_min_obs= min(Taille_MM),
    Taille_max_obs = max(Taille_MM)) %>%
  reframe(Taille=seq(from=Taille_min_obs, to=Taille_max_obs, by=10)) %>% 
  ungroup() %>%
	inner_join(RTP_SIH %>% select(NomScientifique=NOM_VALIDE, RTP_COEF_A_CM, RTP_COEF_B, origine)) %>%
	mutate(Poids=RTP_COEF_A_CM*Taille^RTP_COEF_B)



data_coherente_SIH %>%
  pull(NomVernaculaire) %>%
  unique() %>%
  lapply(function(sp) {

    origine_sp <- data_coherente_SIH %>%
      filter(NomVernaculaire == sp) %>%
      pull(origine) %>%
      unique()

    subtitle_text <- paste0(
      "origine des données : ",
      ifelse(is.na(origine_sp), "NA", origine_sp))

    ggplot() +
      geom_line(
        data = data_coherente_SIH_clean %>% filter(NomVernaculaire == sp),
        aes(x = Taille, y = Poids),
        color = "purple", size = 1) +
      geom_point(
        data = data_coherente_SIH %>% filter(NomVernaculaire == sp),
        aes(x = Taille_MM, y = Poids_g, color = diag)) +
      labs(
        title = sp,
        subtitle = subtitle_text,
        x = "Taille (mm)",
        y = "Poids (g)") +
      scale_color_manual(
        name = NULL,
        values = c(
          "val. ok / RTP ok" = "green",
          "val. ok / RTP inconnue" = "darkgreen",
          "val. ok / RTP aberrante" = "orange",
          "Val. manquante" = "red")) +
      theme_bw() +
      theme(legend.position = "bottom")

  })

```

### RTP fishbase
```{r}

# attention il faut passer en cm car la bse de donnée est en cm. 

data_coherente_FB<- data_coherente%>%
  mutate(Taille_MM = Taille_MM/10, 
         Taille_max_mm=Taille_max_mm/10) %>%
  rename(Taille_CM= Taille_MM,
         Taille_max_CM=Taille_max_mm)



data_coherente_FB <- data_coherente_FB %>%
  mutate(outlier_valeur= Taille_CM==0 | Poids_g==0) %>%
  
  left_join(RTP_fishbase %>% select(NomScientifique=Species, a, b, origine)) %>% # ajouter les coeff  dans le tableau 
  
  mutate(Poids_RTP=a*Taille_CM^b) %>% # calculer le poids théorique grâce aux données de taille et aux coeff 
  
  mutate(Poids_diff = abs(Poids_g- Poids_RTP)) %>% # diff entre poids reel et poids théo
  
  mutate(outlier_RTP=Poids_diff/Poids_RTP > 1) %>% # met dans outlier_rtp les lignes ou poids obs vs poids théo >100%
  
	mutate(outlier=outlier_valeur | outlier_RTP) %>% # rassemble les outlier de zéro et les outlier de poids 

  mutate(diag=ifelse(outlier_valeur, "Val. manquante", "val. ok")) %>%
	mutate(diag=ifelse(! outlier_valeur, paste0(diag, " / ", 
																							ifelse(is.na(outlier_RTP), "RTP inconnue", 
																										 ifelse(outlier_RTP, "RTP aberrante", 'RTP ok'))), diag))  
  

data_coherente_FB_clean <- data_coherente_FB %>%
  filter(!outlier_valeur) %>% # on enlève les outlier = true  : donc on enlève les lignes avec poids ou taille manquante
  group_by(NomVernaculaire, NomScientifique, CodeFAO) %>%
  summarise(
    Taille_min_obs= min(Taille_CM),
    Taille_max_obs = max(Taille_CM)) %>%
  reframe(Taille=seq(from=Taille_min_obs, to=Taille_max_obs, by=10)) %>% 
  ungroup() %>%
	inner_join(RTP_fishbase %>% select(NomScientifique=Species, a, b, origine)) %>%
	mutate(Poids=a*Taille^b)



data_coherente_FB %>%
  pull(NomVernaculaire) %>%
  unique() %>%
  lapply(function(sp) {

    origine_sp <- data_coherente_FB %>%
      filter(NomVernaculaire == sp) %>%
      pull(origine) %>%
      unique()

    subtitle_text <- paste0(
      "origine des données : ",
      ifelse(is.na(origine_sp), "NA", origine_sp))
    
    ggplot() +
      geom_line(
        data = data_coherente_FB_clean %>% filter(NomVernaculaire == sp),
        aes(x = Taille, y = Poids),
        color = "brown", size = 1) +
      geom_point(
        data = data_coherente_FB %>% filter(NomVernaculaire == sp),
        aes(x = Taille_CM, y = Poids_g, color = diag)) +
      labs(
        title = sp,
        subtitle = subtitle_text,
        x = "Taille (cm)",
        y = "Poids (g)") +
      scale_color_manual(
        name = NULL,
        values = c(
          "val. ok / RTP ok" = "green",
          "val. ok / RTP inconnue" = "darkgreen",
          "val. ok / RTP aberrante" = "orange",
          "Val. manquante" = "red")) +
      theme_bw() +
      theme(legend.position = "bottom")

  })



```
### RTP obsbio 

```{r}
# calcul RTP obsbio


# attention il faut passer en cm car la bse de donnée est en cm. 

data_coherente_obsbio <- data_coherente%>%
  filter(NomScientifique %in% RTP_obsbio$NomScientifique)%>%
  left_join(RTP_obsbio %>% select(NomScientifique, a, b, origine))

data_coherente_obsbio<- data_coherente_obsbio%>%
  mutate(Taille_MM = Taille_MM/10, 
         Taille_max_mm=Taille_max_mm/10) %>%
  rename(Taille_CM= Taille_MM,
         Taille_max_CM=Taille_max_mm) %>%
  mutate(origine ="med")



data_coherente_obsbio <- data_coherente_obsbio %>%
  mutate(outlier_valeur= Taille_CM==0 | Poids_g==0) %>%
  
  mutate(Poids_RTP=a*Taille_CM^b) %>% # calculer le poids théorique grâce aux données de taille et aux coeff 
  
  mutate(Poids_diff = abs(Poids_g- Poids_RTP)) %>% # diff entre poids reel et poids théo
  
  mutate(outlier_RTP=Poids_diff/Poids_RTP > 1) %>% # met dans outlier_rtp les lignes ou poids obs vs poids théo >100%
  
	mutate(outlier=outlier_valeur | outlier_RTP) %>% # rassemble les outlier de zéro et les outlier de poids 

  mutate(diag=ifelse(outlier_valeur, "Val. manquante", "val. ok")) %>%
	mutate(diag=ifelse(! outlier_valeur, paste0(diag, " / ", 
																							ifelse(is.na(outlier_RTP), "RTP inconnue", 
																										 ifelse(outlier_RTP, "RTP aberrante", 'RTP ok'))), diag))  
  

data_coherente_obsbio_clean <- data_coherente_obsbio %>%
  filter(!outlier_valeur) %>% # on enlève les outlier = true  : donc on enlève les lignes avec poids ou taille manquante
  group_by(NomVernaculaire, NomScientifique, CodeFAO) %>%
  summarise(
    Taille_min_obs= min(Taille_CM),
    Taille_max_obs = max(Taille_CM)) %>%
  reframe(Taille=seq(from=Taille_min_obs, to=Taille_max_obs, by=10)) %>% 
  ungroup() %>%
  inner_join(RTP_obsbio %>% select(NomScientifique, a, b)) %>%
	mutate(Poids=a*Taille^b)







data_coherente_obsbio %>%
  pull(NomVernaculaire) %>%
  unique() %>%
  lapply(function(sp) {

    origine_sp <- data_coherente_obsbio %>%
      filter(NomVernaculaire == sp) %>%
      pull(origine) %>%
      unique()

    subtitle_text <- paste0(
      "origine des données : ",
      ifelse(is.na(origine_sp), "NA", origine_sp))
    
    ggplot() +
      geom_line(
        data = data_coherente_obsbio_clean %>% filter(NomVernaculaire == sp),
        aes(x = Taille, y = Poids),
        color = "blue", size = 1) +
      geom_point(
        data = data_coherente_obsbio %>% filter(NomVernaculaire == sp),
        aes(x = Taille_CM, y = Poids_g, color = diag)) +
      labs(
        title = sp,
        subtitle = subtitle_text,
        x = "Taille (cm)",
        y = "Poids (g)") +
      scale_color_manual(
        name = NULL,
        values = c(
          "val. ok / RTP ok" = "green",
          "val. ok / RTP inconnue" = "darkgreen",
          "val. ok / RTP aberrante" = "orange",
          "Val. manquante" = "red")) +
      theme_bw() +
      theme(legend.position = "bottom")

  })




```



### combiner les 3 RTP 

```{r}

select_sih <- RTP_SIH %>%
  select(spp=NOM_VALIDE, SIH_RTP_COEF_A_CM=RTP_COEF_A_CM, SIH_RTP_COEF_B=RTP_COEF_B, origine_SIH = origine)
select_FB <- RTP_fishbase %>%
  select(spp=Species, FB_A_CM=a, FB_B=b, origine_FB= origine)
select_obsbio <- RTP_obsbio%>%
  select(spp = NomScientifique, obsbio_a= a, obsbio_b = b, origine_obsbio = origine)


combinaison <- select_FB %>%
  inner_join(select_sih)%>%
  inner_join(select_obsbio)



combinaison <- data_coherente %>%
  select(spp=NomScientifique, Taille_MM=Taille_MM, Poids_g, NomVernaculaire) %>%
  inner_join(combinaison) %>%
  mutate(SIH_poids=SIH_RTP_COEF_A_CM * (Taille_MM)^SIH_RTP_COEF_B,
         FB_poids=FB_A_CM*(Taille_MM/10)^FB_B, 
         obsbio_poids = obsbio_a * (Taille_MM / 10) ^ obsbio_b )

combinaison_med <- combinaison %>%
  filter(origine_FB == "med") %>%
  filter(origine_SIH == "med") %>%
  filter (origine_obsbio == "med")

combinaison_hors_med <- combinaison %>%
  filter(origine_FB == "hors med") %>%
  filter(origine_SIH == "hors med")

```



####mediterranée 
```{r}


combinaison_med %>%
  pull(spp) %>%
  unique() %>%
  lapply(function(sp) {
    df_sp <- combinaison_med %>% filter(spp == sp)
    nom <- unique(df_sp$NomVernaculaire)

    ggplot(df_sp, aes(x = Taille_MM)) +
      geom_line(aes(y = SIH_poids, color = "SIH"), size = 1) +
      geom_line(aes(y = FB_poids, color = "FB"), size = 1) +
      geom_line(aes(y = obsbio_poids, color = "ObsBio"), size = 1) +
      geom_point(aes(y = Poids_g)) +
  
    scale_color_manual(
      name = "Source",
      values = c("SIH" = "brown", "FB" = "purple", "ObsBio" = "blue") )+
        
      xlab("Taille (mm)") +
      ylab("Poids (g)") +
      theme_bw() +
      theme(legend.position = "right") +
      ggtitle(nom)
  })

```


#### hors mediterranée 
```{r}

combinaison_hors_med %>%
  pull(spp) %>%
  unique() %>%
  lapply(function(sp) {
    df_sp <- combinaison_hors_med %>% filter(spp == sp)
    nom <- unique(df_sp$NomVernaculaire)

    ggplot(df_sp, aes(x = Taille_MM)) +
      geom_line(aes(y = SIH_poids, color = "SIH"), size = 1) +
      geom_line(aes(y = FB_poids, color = "FB"), size = 1) +
      geom_line(aes(y = obsbio_poids, color = "ObsBio"), size = 1) +
      geom_point(aes(y = Poids_g)) +
  
    scale_color_manual(
      name = "Source",
      values = c("SIH" = "brown", "FB" = "purple", "ObsBio" = "blue")
   ) +
      
      
      xlab("Taille (mm)") +
      ylab("Poids (g)") +
      
      theme_bw() +
      theme(legend.position = "right") +
      ggtitle(nom)
  })

```



