---
title: "saisonnalite"
format: html
editor: visual
---
```{r}
library(tidyverse)
library(lubridate)

# par espece 

# coryphene : Coryphaena hippurus
# dorade royale : Sparus aurata
# Serran-chèvre : Serranus cabrilla
# Sar commun : Diplodus sargus
# pageot commun : Pagellus erythrinus
# loup : Dicentrarchus labrax
# dorade grise : Spondyliosoma cantharus
#girelle : Coris julis


data_sp <- data_poids_corrige%>%
  filter(annee==2025)%>%
  filter(NomScientifique== "Sparus aurata")


ordre_mois <- c("janvier", "février", "mars", "avril", "mai", "juin",
                "juillet", "août", "septembre", "octobre", "novembre", "décembre")

nb_mois <- data_sp %>%
  mutate(mois = factor(mois, levels = ordre_mois)) %>%
  group_by(annee, mois) %>%
  summarise(nb_prises = sum(Nb_de_prises, na.rm = TRUE), .groups = "drop") %>%
  arrange(annee, mois)

ggplot(nb_mois, aes(x = mois, y = nb_prises, color = factor(annee), group = annee)) +
  geom_line(linewidth = 1.5, alpha = 0.8) +
  geom_point(size = 3, alpha = 0.9) +
  geom_text(aes(label = nb_prises), 
            vjust = -1.5, size = 3, 
            show.legend = F) +
  scale_y_continuous(
    limits = c(0, NA),              
    expand = expansion(mult = c(0, 0.15))  # on met 15% de marge en hautde l'axe y pour avoir la place pour les labels
  ) +
  labs(title = "Nombre de prises de Pageot par mois",
       subtitle = paste("Total:", sum(data_sp$Nb_de_prises), "prises"),  # ← data_sp au lieu de data_poids_corrige
       x = "Mois", y = "Nombre de prises", 
       color = "Année") +
  theme_minimal() +
  theme(plot.title = element_text(size = 14, face = "bold"),
        axis.text.x = element_text(angle = 30, hjust = 1),
        legend.position = "right")



```
# différences par site
```{r}

nb_mois_zone <- data_sp %>%
  filter(ID_ZoneDePeche %in% c(1,4,7))%>%
  mutate(mois = factor(mois, levels = ordre_mois)) %>%
  group_by(Nom_ZoneDePeche, mois) %>%                         # grouper par zone
  summarise(nb_prises = sum(Nb_de_prises, na.rm = TRUE), .groups = "drop") %>%
  arrange(Nom_ZoneDePeche, mois)

ggplot(nb_mois_zone, aes(x = mois, y = nb_prises, 
                         color = Nom_ZoneDePeche,             # une couleur par zone
                         group = Nom_ZoneDePeche)) +
  geom_line(linewidth = 1.5, alpha = 0.8) +
  geom_point(size = 3, alpha = 0.9) +
  geom_text(aes(label = nb_prises), vjust = -1.5, size = 3, show.legend = F) +
  scale_y_continuous(
    limits = c(0, NA),              
    expand = expansion(mult = c(0, 0.15))  # on met 15% de marge en hautde l'axe y pour avoir la place pour les labels
  ) +
  scale_color_discrete(labels = function(x) str_wrap(x, width = 20)) +  # labels longs
  labs(title = "Nombre de prises de Dorade royale par mois - 2025",
       subtitle = paste("Total:", sum(data_dorade$Nb_de_prises[data_dorade$annee == 2025]), "prises"),
       x = "Mois", y = "Nombre de prises",
       color = "Zone de pêche") +
  theme_minimal() +
  theme(plot.title = element_text(size = 14, face = "bold"),
        axis.text.x = element_text(angle = 30, hjust = 1),
        legend.position = "right")


ggplot(nb_mois_zone, aes(x = mois, y = Nom_ZoneDePeche, fill = nb_prises)) +
  geom_tile(color = "white", linewidth = 0.5) +
  geom_text(aes(label = nb_prises), size = 3, color = "white", fontface = "bold") +
  scale_fill_viridis_c(option = "C", name = "Nb prises") +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 20)) +
  labs(title = "Captures de Loup par zone et par mois - 2025",
       x = NULL, y = NULL) +
  theme_minimal() +
  theme(plot.title  = element_text(size = 13, face = "bold"),
        axis.text.x = element_text(angle = 30, hjust = 1),
        axis.text.y = element_text(size = 9))

```

